### ISSUE TITLE
打开文件夹会卡死崩溃

### ISSUE THREAD

**Issue by flyxyz123** [Greedysky/TTKMusicplayer#100]
windows 10\
2.15.0.0版本，网盘下载的

打开文件夹不管里面有多少文件，不管是什么文件类型，必卡死崩溃。

**Comment by Greedysky** [comment]
我没能复现该问题，不过在选择目录上确实有点问题。不管有没有选中目录，都只取了最外层的路径。

**Comment by flyxyz123** [comment]
> 
> 
> 我没能复现该问题，不过在选择目录上确实有点问题。不管有没有选中目录，都只取了最外层的路径。

确实是这样，我又试了一下，发现打开文件夹打开的是上一层目录，因为上一层目录中子目录里，有导致崩溃的那两个.v2m文件，所以我打开文件夹会卡死崩溃。 #101
