### ISSUE TITLE
打开部分.v2m文件会导致程序崩溃

### ISSUE THREAD

**Issue by flyxyz123** [Greedysky/TTKMusicplayer#101]
windows 10
2.15.0.0版本，网盘下载的

~~从资源管理器拖拽大量.v2m文件会卡死崩溃。~~\
~~mod和xm上千文件都没有问题，其他类型没有测试。~~

~~一些v2m文件以供测试：[v2m.zip](https://github.com/Greedysky/TTKMusicplayer/files/6444540/v2m.zip)~~

见下

**Comment by flyxyz123** [comment]
我找到罪魁祸首了，打开这俩个文件中任何一个程序都会崩溃。
[two_files.zip](https://github.com/Greedysky/TTKMusicplayer/files/6444585/two_files.zip)

**Comment by Greedysky** [comment]
更新了最新的v2m库，解决~
