### ISSUE TITLE
ubuntu 20.04.3 , Qt5.9.9 编译报错

### ISSUE THREAD

**Issue by nova-boop** [Greedysky/TTKMusicplayer#106]
插件：    qt5-plugins-linux-Release.2.15.4.0
Qt版本：Qt5.9.9

编译输出:

16:45:44: 为项目TTKMusicPlayer执行步骤 ...
16:45:44: 正在启动 "/opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake" /home/shenpiao/tools/TTKMusicplayer/TTKMusicPlayer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

**Project MESSAGE: Found lrelease executable: /opt/Qt5.9.9/5.9.9/gcc_64/bin/lrelease
Updating '/home/shenpiao/tools/TTKMusicplayer/TTKLanguage/en.qm'...
    Generated 728 translation(s) (651 finished and 77 unfinished)
    Ignored 637 untranslated source text(s)
Updating '/home/shenpiao/tools/TTKMusicplayer/TTKLanguage/tc.qm'...
    Generated 1409 translation(s) (1400 finished and 9 unfinished)
    Ignored 163 untranslated source text(s)
Updating '/home/shenpiao/tools/TTKMusicplayer/TTKLanguage/cn.qm'...
    Generated 1140 translation(s) (1130 finished and 10 unfinished)
    Ignored 431 untranslated source text(s)
xargs: rename: 没有那个文件或目录
mv: 无法获取'/home/shenpiao/tools/TTKMusicplayer/TTKLanguage/*.ln' 的文件状态(stat): 没有那个文件或目录
16:45:44: 进程"/opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake"正常退出。
16:45:44: 正在启动 "/usr/bin/make" -f /home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/Makefile qmake_all**

cd TTKConfig/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKConfig/TTKConfig.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKConfig/ && /usr/bin/make -f Makefile qmake_all
make[1]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKConfig”
make[1]: 对“qmake_all”无需做任何事。
make[1]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKConfig”
cd TTKUi/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKUi/TTKUi.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKUi/ && /usr/bin/make -f Makefile qmake_all
make[1]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKUi”
make[1]: 对“qmake_all”无需做任何事。
make[1]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKUi”
cd TTKThirdParty/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKThirdParty/TTKThirdParty.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKThirdParty/ && /usr/bin/make -f Makefile qmake_all
make[1]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty”
cd Zlib/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKThirdParty/Zlib/Zlib.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd Zlib/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/Zlib”
cd zlib/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKThirdParty/Zlib/zlib/zlib.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd zlib/ && /usr/bin/make -f Makefile qmake_all
make[3]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/Zlib/zlib”
make[3]: 对“qmake_all”无需做任何事。
make[3]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/Zlib/zlib”
cd ttkzip/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKThirdParty/Zlib/ttkzip/ttkzip.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd ttkzip/ && /usr/bin/make -f Makefile qmake_all
make[3]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/Zlib/ttkzip”
make[3]: 对“qmake_all”无需做任何事。
make[3]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/Zlib/ttkzip”
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/Zlib”
cd TTKDumper/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKThirdParty/TTKDumper/TTKDumper.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKDumper/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/TTKDumper”
make[2]: 对“qmake_all”无需做任何事。
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/TTKDumper”
cd TTKWatcher/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKThirdParty/TTKWatcher/TTKWatcher.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKWatcher/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/TTKWatcher”
make[2]: 对“qmake_all”无需做任何事。
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/TTKWatcher”
cd TTKExtras/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKThirdParty/TTKExtras/TTKExtras.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
**Project MESSAGE: Found Qt web component, build in KuGou module by Qt webengine**
cd TTKExtras/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/TTKExtras”
make[2]: 对“qmake_all”无需做任何事。
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty/TTKExtras”
make[1]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKThirdParty”
cd TTKModule/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKModule/TTKModule.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKModule/ && /usr/bin/make -f Makefile qmake_all
make[1]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKModule”
make[1]: 对“qmake_all”无需做任何事。
make[1]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKModule”
cd TTKService/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKService/TTKService.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKService/ && /usr/bin/make -f Makefile qmake_all
make[1]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKService”
make[1]: 对“qmake_all”无需做任何事。
make[1]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKService”
cd TTKRun/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKRun/TTKRun.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKRun/ && /usr/bin/make -f Makefile qmake_all
make[1]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun”
cd TTKInit/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKRun/TTKInit/TTKInit.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKInit/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKInit”
make[2]: 对“qmake_all”无需做任何事。
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKInit”
cd TTKConsole/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKRun/TTKConsole/TTKConsole.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKConsole/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKConsole”
make[2]: 对“qmake_all”无需做任何事。
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKConsole”
cd TTKApp/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKRun/TTKApp/TTKApp.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKApp/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKApp”
make[2]: 对“qmake_all”无需做任何事。
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKApp”
cd TTKTools/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKRun/TTKTools/TTKTools.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd TTKTools/ && /usr/bin/make -f Makefile qmake_all
make[2]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKTools”
cd url/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKRun/TTKTools/url/url.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd url/ && /usr/bin/make -f Makefile qmake_all
make[3]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKTools/url”
make[3]: 对“qmake_all”无需做任何事。
make[3]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKTools/url”
cd skin/ && /opt/Qt5.9.9/5.9.9/gcc_64/bin/qmake -o Makefile /home/shenpiao/tools/TTKMusicplayer/TTKRun/TTKTools/skin/skin.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd skin/ && /usr/bin/make -f Makefile qmake_all
make[3]: 进入目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKTools/skin”
make[3]: 对“qmake_all”无需做任何事。
make[3]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKTools/skin”
make[2]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun/TTKTools”
make[1]: 离开目录“/home/shenpiao/tools/build-TTKMusicPlayer-Desktop_Qt_5_9_9_GCC_64bit-Debug/TTKRun”
16:45:47: 进程"/usr/bin/make"正常退出。
16:45:47: Elapsed time: 00:03.

**Comment by Greedysky** [comment]
我这边没问题，尝试用qtcreator或者cmake编译

**Comment by py95** [comment]
> 我这个没问题，尝试用qtcreator或者cmake编译

编译好了，目前发现的问题：
1、设置语言没有编译进去，设置语言显示英文
2、播放音乐提示 《应版权方要求，歌曲仅在新酷狗播放器中提供服务》
3、播放歌单报错《TypeError: external.SuperCall is not a function 》

**Comment by py95** [comment]
> > > 我这个没问题，尝试用qtcreator或者cmake编译
> > 
> > 
> > 编译好了，目前发现的问题： 1、设置语言没有编译进去，设置语言显示英文 2、播放音乐提示 《应版权方要求，歌曲仅在新酷狗播放器中提供服务》 3、播放歌单报错《TypeError: external.SuperCall is not a function 》
> 
> 1、看了下你的编译日志，貌似你没有安装 `rename` 命令所致 2、酷狗官方的，暂时没有方法破解， 参考 #17 #56

1、语言设置英文 确实是 没有安装 rename 导致的，安装 rename 后重新编译构建 没有问题
2、3：看来只能作为本地播放器使用了？

**Comment by Greedysky** [comment]
> > > > 我这个没问题，尝试用qtcreator或者cmake编译
> > > 
> > > 
> > > 编译好了，目前发现的问题： 1、设置语言没有编译进去，设置语言显示英文 2、播放音乐提示 《应版权方要求，歌曲仅在新酷狗播放器中提供服务》 3、播放歌单报错《TypeError: external.SuperCall is not a function 》
> > 
> > 
> > 1、看了下你的编译日志，貌似你没有安装 `rename` 命令所致 2、酷狗官方的，暂时没有方法破解， 参考 #17 #56
> 
> 1、语言设置英文 确实是 没有安装 rename 导致的，安装 rename 后重新编译构建 没有问题 2、3：看来只能作为本地播放器使用了？

搜索什么的正常使用，只是酷狗内置的那部分用不了
