### ISSUE TITLE
有个请求

### ISSUE THREAD

**Issue by 715670119** [Greedysky/TTKMusicplayer#107]
大佬能否做个win10 x64平台的绿色便携版（解压即用免安装），并且运行软件后，所产生的缓存、配置、日志等之类的文件，老老实实待在TTKMusicplayer主体文件夹内，而不去c盘乱跑，这意味着哪怕直接把最外层的文件夹丢进U盘，依旧可以运行，且所有设置、缓存等都没有变化，也可以把文件夹直接拖到一台新电脑，直接使用，大佬懂我表达的意思吧

**Comment by Greedysky** [comment]
> 

这个功能可以实现，其实最老的版本就是直接生成在程序主体文件夹内，考虑到版本升级之间配置同步性问题，后期迭代废弃了。

**Comment by 715670119** [comment]
缓存、设置等之类的文件，可以归类都放进一个类似userdata之类的内部文件夹（为了好表达，我暂且命名这个），对于用户来说，更新的话，只要把“Userdata”文件夹拎出来放进新的更新包就行了，小白用安装版，非小白用解压版（话说都上github了应该没小白了吧，把绿色版使用说明写在readme就行了），其实现在网上的风向就是绿色便携，特别是专业破jie的博客，发布资源的，可以说95%以上都是绿色便携了，绿色便携受众其实很多，如今信息开放，真正懂电脑的越来越多，也就越来越“极客”，被当初某些软件荼毒怕了，看着c盘各种文件夹盘根错节就不得劲。所以还望大佬额外编译个绿色便携版~

**Comment by Greedysky** [comment]
> 缓存、设置等之类的文件，可以归类都放进一个类似userdata之类的内部文件夹（为了好表达，我暂且命名这个），对于用户来说，更新的话，只要把“Userdata”文件夹拎出来放进新的更新包就行了，小白用安装版，非小白用解压版（话说都上github了应该没小白了吧，把绿色版使用说明写在readme就行了），其实现在网上的风向就是绿色便携，特别是专业破jie的博客，发布资源的，可以说95%以上都是绿色便携了，绿色便携受众其实很多，如今信息开放，真正懂电脑的越来越多，也就越来越“极客”，被当初某些软件荼毒怕了，看着c盘各种文件夹盘根错节就不得劲。所以还望大佬额外编译个绿色便携版~

以后Windows 出两个版本，安装版和便携版

**Comment by Greedysky** [comment]
done!
