### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Kakueeen** [Greedysky/TTKMusicplayer#109]
Qt 版本：5.11.3
插件版本：qt5-plugins-linux-Release.2.15.8.0

日志：
`make[1]: Entering directory '/home/uos/WorkSpace/github/build-TTKMusicPlayer-unknown-Debug/TTKService'
g++  -o ../bin/2.15.8.0/TTKService .build/obj/ttkdesktopwrapper.o .build/obj/musicservicemain.o   -L/home/uos/WorkSpace/github/build-TTKMusicPlayer-unknown-Debug/TTKService/../bin/2.15.8.0 -lTTKqmmp -lTTKUi -lTTKExtras -lTTKWatcher -lTTKDumper -lzlib -lTTKZip -lTTKCore -lTTKConfig -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Xml -lQt5Network -lQt5DBus -lQt5Core -lGL -lpthread 
/usr/bin/ld: /home/uos/WorkSpace/github/build-TTKMusicPlayer-unknown-Debug/TTKService/../bin/2.15.8.0/libTTKqmmp.so: undefined reference to '__cxa_throw_bad_array_new_length@Qt_5'
collect2: error: ld returned 1 exit status
make[1]: Leaving directory '/home/uos/WorkSpace/github/build-TTKMusicPlayer-unknown-Debug/TTKService'
make[1]: *** [Makefile:185: ../bin/2.15.8.0/TTKService] Error 1
make: *** [Makefile:222: sub-TTKService-make_first-ordered] Error 2
18:11:36: 进程"/usr/bin/make"退出，退出代码 2 。
Error while building/deploying project TTKMusicPlayer (kit: 桌面)
When executing step "Make"`

**Comment by Kakueeen** [comment]
undefined reference to '__cxa_throw_bad_array_new_length@Qt_5'

**Comment by Greedysky** [comment]
qt5-plugins-linux-Release.2.15.8.0 是基于Qt5.9.9版本，需对应版本。当然也可以用Qt5.11.3版本，这样需要自己编译插件。
