### ISSUE TITLE
有个问题和几个希望优化的点

### ISSUE THREAD

**Issue by aDon0000** [Greedysky/TTKMusicPlayer#110]
问题
1、搜索栏，搜索1，2次后就无法输入中文了。WIN11 系统自带输入法
优化
1、音乐云盘是存到哪里的啊，要是存到自己的OneDrive就很好
2、搜索列表加载有点慢，切换搜索源不方便

另外，手机APP在哪里下啊

**Comment by Greedysky** [comment]
已优化搜索列表加载
