### ISSUE TITLE
4月开始酷我音乐库好像也无法下载播放了

### ISSUE THREAD

**Issue by shuiyueyoumeng12** [Greedysky/TTKMusicPlayer#118]
您好，好像从4月份开始，酷我库好像也和酷狗一样无法下载以及播放了，下载提示用官方软件下载播放，是否是酷我库过老没有更新导致？

**Comment by Greedysky** [comment]
应该是官方改了接口，有时间我看一下。

**Comment by shuiyueyoumeng12** [comment]
> 应该是官方改了接口，有时间我看一下。

辛苦了，也是这一两天的事情，我看了下别的第三方软件也是一样的问题，估计是改了

**Comment by Greedysky** [comment]
> 

KW已修复，过两天看下KG的。
