### ISSUE TITLE
Support projectm v4

### ISSUE THREAD

**Issue by chenrui333** [Greedysky/TTKMusicPlayer#119]
👋 Not sure if this is the right place, but I found this repo via [qmmp one](https://github.com/Greedysky/qmmp), I was running into some issue of trying to upgrade projectm to v4, and it seems there is some regression test failure with qmmp.

```
  ==> pkg-config sdl2 --cflags --libs
  ==> /usr/bin/g++-11 -std=c++11 test.cpp -o test -I/home/linuxbrew/.linuxbrew/Cellar/projectm/4.0.0/include -L/home/linuxbrew/.linuxbrew/Cellar/projectm/4.0.0/lib -lprojectM-4 -lGL -D_REENTRANT -I/home/linuxbrew/.linuxbrew/include/SDL2 -L/home/linuxbrew/.linuxbrew/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -Wl,--enable-new-dtags -lSDL2
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/projectm/4.0.0/lib/libprojectM-4.so: undefined reference to `glGetInternalformativ'
  collect2: error: ld returned 1 exit status
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4645493634/jobs/8242336467
relates to https://github.com/Homebrew/homebrew-core/pull/127357

cc @hartwork

**Comment by Greedysky** [comment]
Done!
