### ISSUE TITLE
在ArchLinux上无法运行

### ISSUE THREAD

**Issue by zxp19821005** [Greedysky/TTKMusicPlayer#120]
我根据[Release](https://github.com/Greedysky/TTKMusicPlayer/releases/tag/3.3.0.0) 页面上发布的Linux编译文件在ArchLinux下进行了移植：[ttkmusicplayer-bin](https://aur.archlinux.org/packages/ttkmusicplayer-bin)。运行后提示内容如下：
`chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/../TTKRoutine.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKInit.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/../TTKMusicPlayer.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKConsole.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKService.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKRoutineCopy.sh' 的权限: 不允许的操作
[2023-05-06 10:56:52:119][W][../../../../TTKMusicPlayer/TTKRun/TTKApp/ttkrunobject.cpp(67)]  Application exit success`
软件弹出一个界面后直接就退出了。
相应的文件全部给了755的权限。

**Comment by Greedysky** [comment]
Linux编译文件在ArchLinux下解压 ./AppRun 就可以执行
ArchLinux 5.8.10-arch1-1 GNOME环境

**Comment by zxp19821005** [comment]
是的，解压到个人用户可写的目录都可以正常运行，但是将其打包为安装包，安装到/opt目录后，并按照通行的权限标准，将目录属主设置为root，目录权限设置为755，一般性文件权限设置为644，TTK开头的文件设置为755之后，无法运行。
可以查看我的PKGBUILD文件：https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttkmusicplayer-bin

**Comment by Greedysky** [comment]
好的，这两天我看一下

**Comment by zxp19821005** [comment]
谢谢！

**Comment by zxp19821005** [comment]
具体的代码这块我不太懂，我觉得是不是能够做一个检测，提示使用者修改权限，而不是直接修改权限呢？

**Comment by Greedysky** [comment]
@zxp19821005 @flyxyz123  权限这块后面优化下，另外帮忙看下 `TTKService` 能不能启动，若不能请把终端的日志 Post 上来我看看。

**Comment by Greedysky** [comment]
从这个日志来看，感觉像是webengine挂了

**Comment by zxp19821005** [comment]
我运行的结果如下：
`$ /opt/ttkmusicplayer/3.3.0.0/TTKService.sh 
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/../TTKRoutine.sh' 的权限: 不允许的操作chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKInit.sh' 的权限: 不允许的操作chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/../TTKMusicPlayer.sh' 的权限: 不允许的操作chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKConsole.sh' 的权限: 不允许的操作chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKService.sh' 的权限: 不允许的操作chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKRoutineCopy.sh' 的权限: 不允许的操作[2023-05-10 08:41:52:901][W][../../../TTKMusicPlayer/TTKModule/TTKCore/musicCoreKits/musicruntimemanager.cpp(92)]  MusicApplication Run
[2023-05-10 08:41:52:908][W][../../../TTKMusicPlayer/TTKModule/TTKCore/musicNetworkKits/tools/musicnetworkthread.cpp(31)]  Load NetworkThread




[2023-05-10 08:42:43:705][W][../../../TTKMusicPlayer/TTKModule/TTKCore/musicNetworkKits/music/wy/musicwydiscoverlistrequest.cpp(12)]  MusicWYDiscoverListRequest startToSearch
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function SSLeay
qt.network.ssl: Incompatible version of OpenSSL
[2023-05-10 08:42:43:742][W][../../../TTKMusicPlayer/TTKModule/musicapplicationmodule.cpp(104)]  Application network support ssl: false
QmmpPluginCache: loaded plugin libsoxr.so
QmmpPluginCache: loaded plugin libsrconverter.so
QmmpPluginCache: loaded plugin libbitcrusher.so
QmmpPluginCache: loaded plugin libbs2b.so
QmmpPluginCache: loaded plugin libcrystalizer.so
QmmpPluginCache: loaded plugin libecho.so
QmmpPluginCache: loaded plugin libladspa.so
QmmpPluginCache: loaded plugin libmixer.so
QmmpPluginCache: loaded plugin libmuffler.so
QmmpPluginCache: loaded plugin libsilence.so
QmmpPluginCache: loaded plugin libsonic.so
QmmpPluginCache: loaded plugin libstereo.so
QmmpPluginCache: loaded plugin libsubwoofer.so
QmmpPluginCache: loaded plugin libcrossfade.so
Visual: loaded plugin libfloridancient.so
Visual: loaded plugin libfloridautism.so
Visual: loaded plugin libfloridbass.so
Visual: loaded plugin libfloridelectric.so
Visual: loaded plugin libfloridpicture.so
Visual: loaded plugin libfloridreverb.so
Visual: loaded plugin libfloridsurround.so
Visual: loaded plugin libflowgoom.so
Visual: loaded plugin libflowinfinity.so
Visual: loaded plugin libflowmatrix.so
Visual: loaded plugin libflowmountain.so
Visual: loaded plugin libflowprojectm.so
Visual: loaded plugin libflowsonique.so
Visual: loaded plugin libflowvumeter.so
Visual: loaded plugin libnormalanalyzer.so
Visual: loaded plugin libnormalewave.so
Visual: loaded plugin libnormalflowwave.so
Visual: loaded plugin libnormalhistogram.so
Visual: loaded plugin libnormalline.so
Visual: loaded plugin libouterblurwave.so
Visual: loaded plugin libouterrayswave.so
Visual: loaded plugin libouterripples.so
Visual: loaded plugin libplusblurxrays.so
Visual: loaded plugin libplusfoldwave.so
Visual: loaded plugin libplusxrays.so
Visual: loaded plugin libwavecrest.so
Visual: loaded plugin libwavevoice.so
Visual: loaded plugin libwavevolume.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libbitcrusher.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libbs2b.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libcrossfade.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libcrystalizer.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libecho.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libladspa.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libmixer.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libmuffler.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libsilence.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libsonic.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libsoxr.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libsrconverter.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libstereo.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Effect/libsubwoofer.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libaac.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libadlmidi.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libadplug.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libarchive.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libasap.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libayfly.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libcdaudio.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libcue.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libdca.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libfc14.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libffap.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libffmpeg.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libflac.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libgme.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libhively.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libken.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libmpc.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libmpeg.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libopenmpt.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/liboptimfrog.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libopus.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/liborganya.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libpsf.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libs98.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libsc68.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libsid.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libsndfile.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libsoundmon.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libstsound.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libsunvox.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libtfmx.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libuade.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libv2m.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libvorbis.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libwavpack.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libxmdx.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libxmp.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Input/libxsf.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Transports/libhttp.so
QmmpPluginCache: removed key home/zxp-cachyos/Downloads/3.3.0.0/plugins/Transports/libnetwork.so
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("http://greedysky-data.oss-cn-shanghai.aliyuncs.com/version")
[2023-05-10 08:42:43:833][W][../../../TTKMusicPlayer/TTKModule/musicrightareawidget.cpp(188)]  Current in lrc parser mode
QFSFileEngine::open: No file name specified
Qt WebEngine ICU data not found at /home/greedysky/Software/Qt5.9.9/5.9.9/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/greedysky/Software/Qt5.9.9/5.9.9/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/greedysky/Software/Qt5.9.9/5.9.9/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /opt/ttkmusicplayer/3.3.0.0/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/zxp-cachyos/.TTKMusicPlayer'
Qt WebEngine resources not found at /home/greedysky/Software/Qt5.9.9/5.9.9/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/greedysky/Software/Qt5.9.9/5.9.9/gcc_64. Trying application directory...
[0510/084243.908230:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
LaunchProcess: failed to execvp:
/opt/ttkmusicplayer/3.3.0.0/QtWebEngineProcess
[9384:9384:0510/084243.915357:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). 
#0 0x7f25f025422e <unknown>
#1 0x7f25f0265f3e <unknown>
#2 0x7f25efec5c53 <unknown>
#3 0x7f25efec494b <unknown>
#4 0x7f25efec4eee <unknown>
#5 0x7f25efb7fb2d <unknown>
#6 0x7f25efb833d3 <unknown>
#7 0x7f25ef97df5f <unknown>
#8 0x7f25ef97f265 <unknown>
#9 0x7f25ef918561 QtWebEngineCore::BrowserContextAdapter::defaultContext()
#10 0x7f25f6826ed8 QWebEngineProfile::defaultProfile()
#11 0x7f25f682b969 QWebEngineSettings::defaultSettings()
#12 0x7f25fa865755 QKugouWindow::QKugouWindow()
#13 0x7f25fea453cb MusicRightAreaWidget::createkWebWindow()
#14 0x7f25fea455fa MusicRightAreaWidget::functionClicked()
#15 0x7f25fea4693e MusicRightAreaWidget::musicLoadSongIndexWidget()
#16 0x7f25fea7d3f5 MusicRightAreaWidget::qt_static_metacall()
#17 0x7f25fd0a4549 QMetaObject::activate()
#18 0x7f25fd0b0dc3 <unknown>
#19 0x7f25fd0a545b QObject::event()
#20 0x7f25fd75370c QApplicationPrivate::notify_helper()
#21 0x7f25fd75ab37 QApplication::notify()
#22 0x7f25fd079f68 QCoreApplication::notifyInternal2()
#23 0x7f25fd0cbd4e QTimerInfoList::activateTimers()
#24 0x7f25fd0cc531 <unknown>
#25 0x7f25ff26ee91 g_main_context_dispatch
#26 0x7f25ff2dc929 <unknown>
#27 0x7f25ff26d852 g_main_context_iteration
#28 0x7f25fd0cc86f QEventDispatcherGlib::processEvents()
#29 0x7f25fd07855a QEventLoop::exec()
#30 0x7f25fd080e34 QCoreApplication::exec()
#31 0x0000004028b6 main
#32 0x7f25fc623890 <unknown>
#33 0x7f25fc62394a __libc_start_main
#34 0x000000402d39 _start

[2023-05-10 08:42:43:928][W][../../../../TTKMusicPlayer/TTKCommon/TTKDumper/ttkdumper.cpp(172)]  App error occurred, error code  6`

**Comment by zxp19821005** [comment]
还生成了一个 TTK_3.3.0.0.1683679363.dmp 文件，内容如下：
`/opt/ttkmusicplayer/3.3.0.0/../3.3.0.0/libTTKDumper.so(_ZN16TTKDumperPrivate12errorHandlerEi+0x7b4)[0x7f25ff0052f4]
/usr/lib/libc.so.6(+0x3dad0)[0x7f25fc63dad0]
/usr/lib/libc.so.6(pthread_kill+0x11b)[0x7f25fc69483b]
/usr/lib/libc.so.6(gsignal+0x18)[0x7f25fc63da28]
/usr/lib/libc.so.6(abort+0xd7)[0x7f25fc622538]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0x1053e55)[0x7f25f0253e55]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0x1066115)[0x7f25f0266115]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0xcc5c53)[0x7f25efec5c53]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0xcc494b)[0x7f25efec494b]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0xcc4eee)[0x7f25efec4eee]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0x97fb2d)[0x7f25efb7fb2d]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0x9833d3)[0x7f25efb833d3]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0x77df5f)[0x7f25ef97df5f]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(+0x77f265)[0x7f25ef97f265]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineCore.so.5(_ZN15QtWebEngineCore21BrowserContextAdapter14defaultContextEv+0x11)[0x7f25ef918561]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineWidgets.so.5(_ZN17QWebEngineProfile14defaultProfileEv+0x48)[0x7f25f6826ed8]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5WebEngineWidgets.so.5(_ZN18QWebEngineSettings15defaultSettingsEv+0x9)[0x7f25f682b969]
/opt/ttkmusicplayer/3.3.0.0/../3.3.0.0/libTTKExtras.so(_ZN12QKugouWindowC1ENS_6ModuleEP7QWidget+0x65)[0x7f25fa865755]
/opt/ttkmusicplayer/3.3.0.0/../3.3.0.0/libTTKCore.so(_ZN20MusicRightAreaWidget16createkWebWindowEi+0x19b)[0x7f25fea453cb]
/opt/ttkmusicplayer/3.3.0.0/../3.3.0.0/libTTKCore.so(_ZN20MusicRightAreaWidget15functionClickedEiP7QWidget+0x12a)[0x7f25fea455fa]
/opt/ttkmusicplayer/3.3.0.0/../3.3.0.0/libTTKCore.so(_ZN20MusicRightAreaWidget24musicLoadSongIndexWidgetEv+0x14e)[0x7f25fea4693e]
/opt/ttkmusicplayer/3.3.0.0/../3.3.0.0/libTTKCore.so(+0x67d3f5)[0x7f25fea7d3f5]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x659)[0x7f25fd0a4549]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(+0x2b0dc3)[0x7f25fd0b0dc3]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x7b)[0x7f25fd0a545b]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f25fd75370c]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x227)[0x7f25fd75ab37]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x108)[0x7f25fd079f68]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(_ZN14QTimerInfoList14activateTimersEv+0x46e)[0x7f25fd0cbd4e]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(+0x2cc531)[0x7f25fd0cc531]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x141)[0x7f25ff26ee91]
/usr/lib/libglib-2.0.so.0(+0xce929)[0x7f25ff2dc929]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32)[0x7f25ff26d852]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f25fd0cc86f]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xea)[0x7f25fd07855a]
/opt/ttkmusicplayer/3.3.0.0/../lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x84)[0x7f25fd080e34]
/opt/ttkmusicplayer/3.3.0.0/TTKService(main+0x776)[0x4028b6]
/usr/lib/libc.so.6(+0x23890)[0x7f25fc623890]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7f25fc62394a]
/opt/ttkmusicplayer/3.3.0.0/TTKService[0x402d39]`

**Comment by zxp19821005** [comment]
@flyxyz123 确实是，按照你说的方法，修改了PKGBUILD文件，现在运行正常了。谢谢！
@Greedysky 也麻烦你了！
但是在终端运行依然会有以下信息：
`$ /opt/ttkmusicplayer/AppRun 
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/../TTKRoutine.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKInit.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/../TTKMusicPlayer.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKConsole.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKService.sh' 的权限: 不允许的操作
chmod: 更改 '/opt/ttkmusicplayer/3.3.0.0/TTKRoutineCopy.sh' 的权限: 不允许的操作
[2023-05-10 09:02:27:249][W][../../../../TTKMusicPlayer/TTKRun/TTKApp/ttkrunobject.cpp(67)]  Application exit success`

**Comment by Greedysky** [comment]
权限这块后面我优化下 @zxp19821005

**Comment by zxp19821005** [comment]
好的  谢谢！
