### ISSUE TITLE
本地乐库中文乱码

### ISSUE THREAD

**Issue by wuyedefeng9** [Greedysky/TTKMusicPlayer#121]
1、本地乐库中文显示乱码，在foobar2000中显示正常，标签采用musictag，UTF-8
2、乐库在加载专辑时候，建议分级展示专辑及分轨列表，去掉cue文件的显示

**Comment by Greedysky** [comment]
@wuyedefeng9  乱码的文件，能方便提供一下吗？

**Comment by Money001** [comment]
乱码音乐如下，截图里面显示的
https://share.weiyun.com/oyZV2LYj

**Comment by Greedysky** [comment]
![captrue](https://github.com/user-attachments/assets/054502e4-ea1c-47a3-b95c-44a3cbaafe34)
下个版本加入自动检测编码，不需要手动选择，避免编码错误的情况。
