### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wuyedefeng9** [Greedysky/TTKMusicPlayer#122]
1、在线音乐搜索时候，将各来源的搜索结果合并，进行集中展示，简化搜索和下载
2、搜索结果显示音质标签便于选择

**Comment by GJan2002** [comment]
听着歌 其他程序的ctrl+s快捷键失效

**Comment by Greedysky** [comment]
> 听着歌 其他程序的ctrl+s快捷键失效

确实如此，这两天看一下

**Comment by Greedysky** [comment]
> 听着歌 其他程序的ctrl+s快捷键失效
Fixed bf67e06

**Comment by Greedysky** [comment]
> 参数设置后全局热键初始化[450036]？

把全局热键初始化延后了

**Comment by wuyedefeng9** [comment]
> > 1、在线音乐搜索时候，将各来源的搜索结果合并，进行集中展示，简化搜索和下载 2、搜索结果显示音质标签便于选择
> 
> 这些功能更倾向于是个音乐下载器，后期会考虑出个精简版本的

我的本意不是去下载，是便于选择在线音乐的音质选择，当然程序也可以考虑默认按最好的音质来播放
