### ISSUE TITLE
更改软件设置退出软件后不会保存设置

### ISSUE THREAD

**Issue by sbkill1r** [Greedysky/TTKMusicPlayer#128]
更改软件设置退出软件后不会保存设置

**Comment by Greedysky** [comment]
我这边无法复现，请提供更多的复现步骤。

**Comment by sbkill1r** [comment]
emmmmm，之前我点击关闭面板时，软件就直接退出了。我就设置关闭面板最小化，之前设置好像不能保存，点击关闭面板，还是回退出软件，今天我试了一下，好像也不能复现了，保存设置成功了。

**Comment by Greedysky** [comment]
> emmmmm，之前我点击关闭面板时，软件就直接退出了。我就设置关闭面板最小化，之前设置好像不能保存，点击关闭面板，还是回退出软件，今天我试了一下，好像也不能复现了，保存设置成功了。

找到了：**设置最小化到托盘，再托盘处，点击设置，弹出界面后关闭，程序退出软件。**，你之前遇到的应该是这个。

**Comment by Greedysky** [comment]
Fixed 7078d9d41667cc540fbda27d2284ec7423d72d17
