### ISSUE TITLE
Clarification re build procedure

### ISSUE THREAD

**Issue by barracuda156** [Greedysky/TTKMusicPlayer#130]
A couple of quick questions on the build:

1. CMake tries to do something weird during configure, and fails, not being allowed by the OS to mess up directorties.

```
-- Message Found qmake executable: /opt/local/libexec/qt4/bin/qmake
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - found
-- Looking for QT_MAC_USE_COCOA
-- Looking for QT_MAC_USE_COCOA - not found
-- Found Qt4: /opt/local/libexec/qt4/bin/qmake (found version "4.8.7") 
-- Message Found lrelease executable: /opt/local/libexec/qt4/bin/lrelease
mkdir: /bin/3.4.0.0: Permission denied
Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/cn.qm'...
    Generated 942 translation(s) (933 finished and 9 unfinished)
    Ignored 424 untranslated source text(s)
Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/cnq.qm'...
    Generated 291 translation(s) (291 finished and 0 unfinished)
Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/en.qm'...
    Generated 703 translation(s) (622 finished and 81 unfinished)
    Ignored 663 untranslated source text(s)
Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/enq.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/tc.qm'...
    Generated 1203 translation(s) (1195 finished and 8 unfinished)
    Ignored 163 untranslated source text(s)
Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/tcq.qm'...
    Generated 291 translation(s) (291 finished and 0 unfinished)
rename: invalid option -- f
Try 'rename --help' for more information.
rename: invalid option -- f
Try 'rename --help' for more information.
rename: invalid option -- f
Try 'rename --help' for more information.
rename: invalid option -- f
Try 'rename --help' for more information.
rename: invalid option -- f
Try 'rename --help' for more information.
rename: invalid option -- f
Try 'rename --help' for more information.
mv: rename /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/*.ln to /bin/3.4.0.0/GLanguage: No such file or directory
mkdir: /bin/3.4.0.0: Permission denied
cp: /bin/3.4.0.0/TTKInit.sh: No such file or directory
cp: /bin/3.4.0.0/../TTKMusicPlayer.sh: No such file or directory
cp: /bin/3.4.0.0/../TTKRoutine.sh: No such file or directory
cp: /bin/3.4.0.0/TTKConsole.sh: No such file or directory
cp: /bin/3.4.0.0/TTKService.sh: No such file or directory
cp: /bin/3.4.0.0/TTKRoutineCopy.sh: No such file or directory
```
Could we turn this behavior off?

2. What should be used for `TTK_QMMP_LIBRARY`? Some actual pre-installed library? A path to `TTKMusicPlayer` own third party dir?
```
-- Found Qt4: /opt/local/libexec/qt4/bin/qmake (found version "4.8.7") 
-- Message Found QT_WEBKIT_MODULE component, build in KuGou by Qt webkit
-- Configuring done (12.6s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TTK_QMMP_LIBRARY
    linked by target "TTKCore" in directory /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKModule

-- Generating done (2.9s)
```

**Comment by Greedysky** [comment]
> A couple of quick questions on the build:
> 
>     1. CMake tries to do something weird during configure, and fails, not being allowed by the OS to mess up directorties.
> 
> 
> ```
> -- Message Found qmake executable: /opt/local/libexec/qt4/bin/qmake
> -- Looking for Q_WS_X11
> -- Looking for Q_WS_X11 - not found
> -- Looking for Q_WS_WIN
> -- Looking for Q_WS_WIN - not found
> -- Looking for Q_WS_QWS
> -- Looking for Q_WS_QWS - not found
> -- Looking for Q_WS_MAC
> -- Looking for Q_WS_MAC - found
> -- Looking for QT_MAC_USE_COCOA
> -- Looking for QT_MAC_USE_COCOA - not found
> -- Found Qt4: /opt/local/libexec/qt4/bin/qmake (found version "4.8.7") 
> -- Message Found lrelease executable: /opt/local/libexec/qt4/bin/lrelease
> mkdir: /bin/3.4.0.0: Permission denied
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/cn.qm'...
>     Generated 942 translation(s) (933 finished and 9 unfinished)
>     Ignored 424 untranslated source text(s)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/cnq.qm'...
>     Generated 291 translation(s) (291 finished and 0 unfinished)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/en.qm'...
>     Generated 703 translation(s) (622 finished and 81 unfinished)
>     Ignored 663 untranslated source text(s)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/enq.qm'...
>     Generated 0 translation(s) (0 finished and 0 unfinished)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/tc.qm'...
>     Generated 1203 translation(s) (1195 finished and 8 unfinished)
>     Ignored 163 untranslated source text(s)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/tcq.qm'...
>     Generated 291 translation(s) (291 finished and 0 unfinished)
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> mv: rename /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/*.ln to /bin/3.4.0.0/GLanguage: No such file or directory
> mkdir: /bin/3.4.0.0: Permission denied
> cp: /bin/3.4.0.0/TTKInit.sh: No such file or directory
> cp: /bin/3.4.0.0/../TTKMusicPlayer.sh: No such file or directory
> cp: /bin/3.4.0.0/../TTKRoutine.sh: No such file or directory
> cp: /bin/3.4.0.0/TTKConsole.sh: No such file or directory
> cp: /bin/3.4.0.0/TTKService.sh: No such file or directory
> cp: /bin/3.4.0.0/TTKRoutineCopy.sh: No such file or directory
> ```
> 
> Could we turn this behavior off?
> 
>     2. What should be used for `TTK_QMMP_LIBRARY`? Some actual pre-installed library? A path to `TTKMusicPlayer` own third party dir?
> 
> 
> ```
> -- Found Qt4: /opt/local/libexec/qt4/bin/qmake (found version "4.8.7") 
> -- Message Found QT_WEBKIT_MODULE component, build in KuGou by Qt webkit
> -- Configuring done (12.6s)
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> TTK_QMMP_LIBRARY
>     linked by target "TTKCore" in directory /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKModule
> 
> -- Generating done (2.9s)
> ```



> A couple of quick questions on the build:
> 
>     1. CMake tries to do something weird during configure, and fails, not being allowed by the OS to mess up directorties.
> 
> 
> ```
> -- Message Found qmake executable: /opt/local/libexec/qt4/bin/qmake
> -- Looking for Q_WS_X11
> -- Looking for Q_WS_X11 - not found
> -- Looking for Q_WS_WIN
> -- Looking for Q_WS_WIN - not found
> -- Looking for Q_WS_QWS
> -- Looking for Q_WS_QWS - not found
> -- Looking for Q_WS_MAC
> -- Looking for Q_WS_MAC - found
> -- Looking for QT_MAC_USE_COCOA
> -- Looking for QT_MAC_USE_COCOA - not found
> -- Found Qt4: /opt/local/libexec/qt4/bin/qmake (found version "4.8.7") 
> -- Message Found lrelease executable: /opt/local/libexec/qt4/bin/lrelease
> mkdir: /bin/3.4.0.0: Permission denied
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/cn.qm'...
>     Generated 942 translation(s) (933 finished and 9 unfinished)
>     Ignored 424 untranslated source text(s)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/cnq.qm'...
>     Generated 291 translation(s) (291 finished and 0 unfinished)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/en.qm'...
>     Generated 703 translation(s) (622 finished and 81 unfinished)
>     Ignored 663 untranslated source text(s)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/enq.qm'...
>     Generated 0 translation(s) (0 finished and 0 unfinished)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/tc.qm'...
>     Generated 1203 translation(s) (1195 finished and 8 unfinished)
>     Ignored 163 untranslated source text(s)
> Updating '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/tcq.qm'...
>     Generated 291 translation(s) (291 finished and 0 unfinished)
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> rename: invalid option -- f
> Try 'rename --help' for more information.
> mv: rename /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKLanguage/*.ln to /bin/3.4.0.0/GLanguage: No such file or directory
> mkdir: /bin/3.4.0.0: Permission denied
> cp: /bin/3.4.0.0/TTKInit.sh: No such file or directory
> cp: /bin/3.4.0.0/../TTKMusicPlayer.sh: No such file or directory
> cp: /bin/3.4.0.0/../TTKRoutine.sh: No such file or directory
> cp: /bin/3.4.0.0/TTKConsole.sh: No such file or directory
> cp: /bin/3.4.0.0/TTKService.sh: No such file or directory
> cp: /bin/3.4.0.0/TTKRoutineCopy.sh: No such file or directory
> ```
> 
> Could we turn this behavior off?
> 
>     2. What should be used for `TTK_QMMP_LIBRARY`? Some actual pre-installed library? A path to `TTKMusicPlayer` own third party dir?
> 
> 
> ```
> -- Found Qt4: /opt/local/libexec/qt4/bin/qmake (found version "4.8.7") 
> -- Message Found QT_WEBKIT_MODULE component, build in KuGou by Qt webkit
> -- Configuring done (12.6s)
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> TTK_QMMP_LIBRARY
>     linked by target "TTKCore" in directory /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_TTKMusicPlayer/TTKMusicPlayer/work/TTKMusicPlayer-3.4.0.0/TTKModule
> 
> -- Generating done (2.9s)
> ```

1. 最近的提交记录我改了些CMake，上述原因是linux下的/opt目录需要用户权限。
2. TTK_QMMP_LIBRARY 是 [qmmp 插件](https://github.com/Greedysky/TTKMusicPlayer/tree/plugins) 编译出来的库。
