### ISSUE TITLE
界面问题

### ISSUE THREAD

**Issue by QiBowen2008** [Greedysky/TTKMusicPlayer#134]
1.触控屏不能点开搜索框
2.高DPI缩放不好

**Comment by Greedysky** [comment]
> 1.触控屏不能点开搜索框 2.高DPI缩放不好

1. 没有触控的屏幕暂时没发测试调试。。
2. 高DPI下部分字体显示有问题，原因是字体以及PointSize的问题。

**Comment by Cold-Stars** [comment]
改成这样就正常了
![image](https://github.com/Greedysky/TTKMusicPlayer/assets/113192545/0a0e5693-1282-47e1-a404-125ff1cd6a12)

**Comment by Greedysky** [comment]
Windows 加了qt.conf 以适配放缩比例。
