### ISSUE TITLE
win7系统64位系统无法正常启动3.5.0.0

### ISSUE THREAD

**Issue by shuiyun235** [Greedysky/TTKMusicPlayer#137]
您好，今天下载最新版本的3.5.0.0版本，点击TTKMusicPlayer.exe文件启动，提示：无法启动该程序，找不到libgcc_s_dw2-1.dll, 尝试重新安装该程序以解决问题.
![QQ截图20240118232046](https://github.com/Greedysky/TTKMusicPlayer/assets/135100723/ba9ba062-bc2d-42cd-b29e-9ace60d53aa5)
3.4.0.0版本并无此问题

**Comment by Itzamana** [comment]
https://cn.dll-files.com/libgcc_s_dw2-1.dll.html
https://cn.dll-files.com/libwinpthread-1.dll.html

缺失的dll文件可以在上面下载，解压后把相关dll文件放在TTKMusicPlayer.exe同目录下就行

**Comment by Greedysky** [comment]
先暂时从3.5.0.0目录里面把这两个文件复制到，TTKMusicPlayer.exe同目录下，晚点我重新打个包。
