### ISSUE TITLE
歌词列表，部分歌曲名称显示乱码

### ISSUE THREAD

**Issue by InvisableMatrix** [Greedysky/TTKMusicPlayer#139]
添加歌词进入默认列表时，部分歌曲名称显示为乱码。
![image](https://github.com/Greedysky/TTKMusicPlayer/assets/154484064/1f7c2d3c-7246-46d5-aa0b-d985dbccf7eb)

**Comment by Greedysky** [comment]
把乱码的文件发我份 @InvisableMatrix

**Comment by Greedysky** [comment]
通过设置插件元数据编码
![captrue](https://github.com/Greedysky/TTKMusicPlayer/assets/7044256/af08f10b-6e81-4918-be70-95f4e7a0f2fd)

**Comment by InvisableMatrix** [comment]
Thank you so much.

**Comment by Greedysky** [comment]
通过设置插件自动检测编码。
![captrue](https://github.com/user-attachments/assets/26efa156-f058-4bee-b4bc-36652cb0be95)
