### ISSUE TITLE
有些歌曲不能播放

### ISSUE THREAD

**Issue by ichat001** [Greedysky/TTKMusicPlayer#141]
我经常遇到一种情况, 搜索到的歌曲, 双击后不能播放, 改了来源也不行, 例如下面这歌:
赵洋 - 负我不负她 

![A](https://github.com/Greedysky/TTKMusicPlayer/assets/166457982/137bacd6-e028-4acc-843a-1885970460d7)

**Comment by ichat001** [comment]
> 播放不了就是没有版权

没有别的办法解决吗? 这种情况还不少

**Comment by Greedysky** [comment]
> > 播放不了就是没有版权
> 
> 没有别的办法解决吗? 这种情况还不少

是的，毕竟是免费的，还是不能和会员比的。

**Comment by Greedysky** [comment]
> > 播放不了就是没有版权
> 
> 没有别的办法解决吗? 这种情况还不少

这两天计划发布个新版本，某W的你说的情况会有所改善。

**Comment by ichat001** [comment]
> > > 播放不了就是没有版权
> > 
> > 
> > 没有别的办法解决吗? 这种情况还不少
> 
> 发布个新版本，某W的你说的情况会有所改善。@ichat001

刚下载了最新版, 还是不行, 
对于没有版权不能播放的歌曲, 应该直接给个提示, 
下面这首歌曲, 双击搜索到的关于赵洋的歌一首都不能放, 也没任何提示, 真是怪了, 我用别的免费的, 一点就播放
赵洋 负我不负她

**Comment by Greedysky** [comment]
> > > > 播放不了就是没有版权
> > > 
> > > 
> > > 没有别的办法解决吗? 这种情况还不少
> > 
> > 
> > 发布个新版本，某W的你说的情况会有所改善。@ichat001
> 
> 刚下载了最新版, 还是不行, 对于没有版权不能播放的歌曲, 应该直接给个提示, 下面这首歌曲, 双击搜索到的关于赵洋的歌一首都不能放, 也没任何提示, 真是怪了, 我用别的免费的, 一点就播放 赵洋 负我不负她

你确定是最新3.7.0.0的？ 我这边可以下载，另外无版权的会提示 “没有找到相关资源”。
