### ISSUE TITLE
编译缺少头文件

### ISSUE THREAD

**Issue by qq88797833** [Greedysky/TTKMusicPlayer#142]
![image](https://github.com/Greedysky/TTKMusicPlayer/assets/28855943/3ad2f95a-a9bb-4a07-a61a-819db48954bb)

**Comment by qq88797833** [comment]
请问这个代码完整吗，编译好多地方缺少文件

**Comment by Greedysky** [comment]
插件模块自己编译的话，自己编译第三方库，或者用我编译好的。 [详细WIKI](https://github.com/Greedysky/TTKMusicPlayer/wiki/Qmmp%E6%8F%92%E4%BB%B6%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E)
