### ISSUE TITLE
歌词不能下载吗

### ISSUE THREAD

**Issue by leyin863** [Greedysky/TTKMusicPlayer#143]
点下载后，提示正在下载歌词，没反应

**Comment by Greedysky** [comment]
截图给我看看

**Comment by leyin863** [comment]
![IMG_20240508_234109](https://github.com/Greedysky/TTKMusicPlayer/assets/72383783/9b2374e5-3b8b-4396-9239-3f9da7797a9c)

**Comment by Greedysky** [comment]
我这边可以下，你其他的可以下吗？
