### ISSUE TITLE
新增：拖动本地文件夹到 天天音乐 自动生成播放列表，可批量添加

### ISSUE THREAD

**Issue by Money001** [Greedysky/TTKMusicPlayer#147]
我主要做本地播放器使用，下载了很多音乐，文件夹也多，每次新建播放列表，再导入，太麻烦了。
建议新增一个功能：
拖动文件夹，天天音乐 自动生成对应文件夹名字的播放列表，这样就很方便。
另外支持 批量拖动文件夹，一次性就可以导入很多文件夹，更方便。
![新增，拖动文件夹自动生成播放列表](https://github.com/user-attachments/assets/fa728424-d877-47da-a262-a84a8e3b9118)

**Comment by Greedysky** [comment]
已完成，下个版本加入。
