### ISSUE TITLE
网络播放列表，只会单曲循环。不会自动下一首，其它模式都不行，只重复播放选择的那一首

### ISSUE THREAD

**Issue by Money001** [Greedysky/TTKMusicPlayer#149]
网络播放列表，不会自动下一首。设置了其它模式也不行，只重复播放选择的那一首。
手动下一首，仍然只会循环播放以后，只会单曲循环。
我是从 歌单里面，全选，添加到网络列表。
![只会单曲循环](https://github.com/user-attachments/assets/a8397dd8-0a0a-4829-9c8d-4d5727088520)

**Comment by Greedysky** [comment]
在线听的，解析有问题

**Comment by Greedysky** [comment]
Fixed efc06d9fa56ff43f32fe5500158a213c99a6626e
