### ISSUE TITLE
编译qmmp报错

### ISSUE THREAD

**Issue by Lyvnee** [Greedysky/TTKMusicplayer#28]
../../../qmmp-qt5/src/qmmp/tagreadandwrite.cpp:3:28: fatal error: taglib/fileref.h: No such file or directory

**Comment by Greedysky** [comment]
你自己编译qmmp 需要编译这些第三方库
![qq 20160429210011](https://cloud.githubusercontent.com/assets/7044256/14942128/4af806ce-0fe6-11e6-9cd3-46e128d4f70f.png)
![qq 20160429210022](https://cloud.githubusercontent.com/assets/7044256/14942129/4afa736e-0fe6-11e6-95f1-a93144a739f9.png)

**Comment by Greedysky** [comment]
编译教程我已经更新了

**Comment by Lyvnee** [comment]
跑起来了~
