### ISSUE TITLE
搜不到任何歌曲了~

### ISSUE THREAD

**Issue by liguge** [Greedysky/TTKMusicplayer#50]
搜不到歌曲了~

**Comment by Greedysky** [comment]
现在部分可以了。

**Comment by liguge** [comment]
现在还是什么都搜不到，最新版的，比如这个「周杰伦」什么都没有的~

**Comment by Greedysky** [comment]
代码已经改好了，客户端还没有Release， 要过一段时间。另外你可以在下载设置里面改，有备用的。

**Comment by liguge** [comment]
@Greedysky 

请问最近的pc客户端发布了吗？
