### ISSUE TITLE
在windows下不能编译的问题

### ISSUE THREAD

**Issue by maosuyun2009** [Greedysky/TTKMusicplayer#53]
今天看到了这个开源项目，很强大的样子，在尝试放到自己的机器上编译的时候出现了下面的错误：
cd TTKQrc\ && "D:\Program Files\Qt\5.8\mingw53_32\bin\qmake.exe" -o Makefile F:\Qt\Musicplayer\TTKQrc\TTKQrc.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd TTKQrc\ && cd TTKQrc\ && "D:\Program Files\Qt\5.8\mingw53_32\bin\qmake.exe" -o Makefile F:\Qt\Musicplayer\TTKQrc\TTKQrc.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd TTKQrc\ && D:/Program Files/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile qmake_all
'D:/Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Makefile:36: recipe for target 'sub-TTKQrc-qmake_all' failed
mingw32-make: *** [sub-TTKQrc-qmake_all] Error 1
16:14:22: 进程"D:\Program Files\Qt\Tools\mingw530_32\bin\mingw32-make.exe"退出，退出代码 2 。
Error while building/deploying project TTKMusicPlayer (kit: Desktop Qt 5.8.0 MinGW 32bit)
When executing step "qmake" -f Makefile qmake_all
'D:/Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Makefile:36: recipe for target 'sub-TTKQrc-qmake_all' failed
mingw32-make: *** [sub-TTKQrc-qmake_all] Error 1
16:14:22: 进程"D:\Program Files\Qt\Tools\mingw530_32\bin\mingw32-make.exe"退出，退出代码 2 。
Error while building/deploying project TTKMusicPlayer (kit: Desktop Qt 5.8.0 MinGW 32bit)
When executing step "qmake"

似乎是跟我安装的mingw32-make目录存在空格有关系，但是我编译其它工程项目的时候都很正常，有没有什么办法我在想也许给Program Files中间加上转义斜杠或者整个路径加上双引号能解决，但是看了下Makefile，没有找到$(MAKE)这个变量是在哪里，不知道有没有知道怎么解决这个问题的

**Comment by Greedysky** [comment]
Makefile中的QMAKE这个变量 指定了qmake可执行的路径。
另外建议你把QT装在不含空格或者中文路径的目录下。
