### ISSUE TITLE
qmmp插件编译

### ISSUE THREAD

**Issue by maosuyun2009** [Greedysky/TTKMusicplayer#54]
您好，我在尝试自己编译qmmp插件的时候，使用MSYS+mingw的环境；但是在编译projectM这个库的时候总是编译不过去；如果不修改projectM里面一些编译选项的话，我发现编译到后面依赖了一些FTGL库，然后又要freetype库，甚至opengl库都要用上了，编译到opengl实在编译不下去了，就尝试了修改projectM这个库的CMakeList.txt里面的编译选项，但是还是总是缺少一些东西；我想请教下您是怎么编译projectM的，是否有对这个库做过一些编译的修改

**Comment by Greedysky** [comment]
好像是要修改，有点不记得了，用到了GLEW扩展库

**Comment by maosuyun2009** [comment]
不知您那边是否还有projectM编译配置相关东西，能不能把CMakeLists.txt里面做的修改告诉我一下

**Comment by Greedysky** [comment]
已经没有了，只有编译好的库。

**Comment by Greedysky** [comment]
@maosuyun2009  我云盘里有所有编译好的链接库，不过projectM有没有都可以，只是做可视化用到的。
