### ISSUE TITLE
fatal: unable to access 'https://github.com/Greedysky/TTKMusicplayer/': Content-Length: in 200 response

### ISSUE THREAD

**Issue by jingle0927** [Greedysky/TTKMusicplayer#58]
deepin@deepin:~$ git clone https://github.com/Greedysky/TTKMusicplayer
正克隆到 'TTKMusicplayer'...
fatal: unable to access 'https://github.com/Greedysky/TTKMusicplayer/': Content-Length: in 200 response

**Comment by Greedysky** [comment]
你网络不佳

**Comment by jingle0927** [comment]
网路一直正常的 其他的都能访问的 翻墙的原因？
