### ISSUE TITLE
停止工作

### ISSUE THREAD

**Issue by EMLVIRUS** [Greedysky/TTKMusicplayer#59]
Environ.

TTK 2.5.1
Windows 10, build 15063.rs2_release.170317-1834

---

当在同一播放列表添加同一路径内数量超过 1K 音频文件时，程序停止工作

![image](https://user-images.githubusercontent.com/16912240/28235372-fc65fb8e-693e-11e7-91ca-76acbb444a60.png)

---

似乎没有 log.txt？

**Comment by Greedysky** [comment]
release 版本的会有dmp file, debug版本才会有log文件
