### ISSUE TITLE
[feature request] 本地元数据优先

### ISSUE THREAD

**Issue by EMLVIRUS** [Greedysky/TTKMusicplayer#61]
我觉得看图更直观：

![image](https://user-images.githubusercontent.com/16912240/28235439-186aafb8-6940-11e7-99a7-b987dc3ca0a9.png)

**Comment by EMLVIRUS** [comment]
此外显示文件名的时候可否考虑从元数据中获取标题、艺术家等信息，直接引用文件名显得很不专业？

**Comment by Greedysky** [comment]
这个主要看个人习惯吧，能从文件中拿到id3信息 那当然是最好不过的。
