### ISSUE TITLE
compile error with undefined reference of agReadAndWrite

### ISSUE THREAD

**Issue by xyz1001** [Greedysky/TTKMusicplayer#66]
> g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o ../lib/2.5.3.0/TTKService .build/obj/musicservicemain.o .build/obj/moc_soundcore.o .build/obj/moc_visual.o .build/obj/moc_statehandler.o .build/obj/moc_metadatamodel.o .build/obj/moc_abstractengine.o .build/obj/moc_qmmpaudioengine_p.o .build/obj/moc_inputsource.o .build/obj/moc_fileinputsource_p.o .build/obj/moc_emptyinputsource_p.o .build/obj/moc_qmmpsettings.o .build/obj/moc_volume.o .build/obj/moc_volumecontrol_p.o .build/obj/moc_outputwriter_p.o   -L/usr/X11R6/lib64 -L../lib/2.5.3.0 -lqmmp -lTTKUi -lTTKExtras -lTTKWatcher -lzlib -L./lib/2.5.3.0 -lTTKCore -lQt5MultimediaWidgets -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Xml -lQt5Sql -lQt5Network -lQt5Core -lGL -lpthread
../lib/2.5.3.0/libTTKCore.so：对‘TagReadAndWrite::getCover() const’未定义的引用
../lib/2.5.3.0/libTTKCore.so：对‘TagReadAndWrite::writeCover(QByteArray const&, int)’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:215: recipe for target '../lib/2.5.3.0/TTKService' failed
make[1]: *** [../lib/2.5.3.0/TTKService] Error 1
make[1]: Leaving directory '/home/zix/Downloads/TTKMusicplayer-2.5.3.0/build/TTKService'
Makefile:122: recipe for target 'sub-TTKService-make_first' failed
make: *** [sub-TTKService-make_first] Error 2

**Comment by xyz1001** [comment]
environment
- gcc6.3 
- qmake 5.6.1 
- deepin linux x86_64 15.4.1

**Comment by jingle0927** [comment]
能否直接提供 deb 或者 appimage

**Comment by Greedysky** [comment]
可以 不过要过段时间。

**Comment by Greedysky** [comment]
@xyz1001 最新版的可以编译了。

**Comment by Lyvnee** [comment]
@Greedysky 编译环境同@xyz1001
` ../../TTKCore/musicCoreKits/musicplayer.cpp: In member function ‘void MusicPlayer::update()’:
../../TTKCore/musicCoreKits/musicplayer.cpp:257:96: error: call of overloaded ‘abs(float)’ is ambiguous
         m_music->setVolume(abs(100 * cosf(m_posOnCircle), (abs(100 * sinf(m_posOnCircle * 0.5f))));
`

**Comment by Lyvnee** [comment]
@Greedysky 终于编译成功了，Google被我翻烂了，不过我根据搜到的资料对源代码进行了部分修改，如下所列：`../../TTKCore/musicCoreKits/musicplayer.cpp:257  修改 abs()->fabs();`
`../../TTKCore/musicLrcKits/musiclrcmakerwidget.cpp:625  修改 false->QTextEdit::AutoNone`
`../../TTKCore/musicLrcKits/musiclrcposterwidget.cpp  增加 #include <math.h>`
`../../TTKCore/musicLrcKits/musiclrcanalysis.cpp  增加 #include <math.h>`

**Comment by Greedysky** [comment]
@Lyvnee  好的。
