### ISSUE TITLE
这个怎么编译啊

### ISSUE THREAD

**Issue by lm741118** [Greedysky/TTKMusicplayer#71]
我是新手，直接用cmake编译总是Message Expected value for TTK_QT_VERSION is either '4' or '5'
，到底怎么操作才是正确的方法啊

**Comment by Greedysky** [comment]
选个QT版本啊 就4或5

**Comment by lowy** [comment]
怎么弄 是要修改CMakeLists.txt吗？

**Comment by Greedysky** [comment]
不需要 在cmake-gui里就可以设置
