### ISSUE TITLE
实在是没看懂这个项目要怎么编译 能否改进一下文档的编译部分呢?

### ISSUE THREAD

**Issue by IsoaSFlus** [Greedysky/TTKMusicplayer#72]
目前的文档我感觉讲的有点乱，怎么一下github 一下百度网盘的，好像也没有一个清晰明了的依赖列表。

**Comment by Greedysky** [comment]
百度网盘的是我自己编译好的插件，如果是你自己编译的话不需要下载云盘的 直接下载相应的依赖包就行了。

**Comment by Greedysky** [comment]
@xin-water  thanks

**Comment by xin-water** [comment]
@Greedysky  no thanks

**Comment by IsoaSFlus** [comment]
@xin-water  感谢您的回复。查看了您的文档，我觉得和作者的文档没有什么区别。
另外 @Greedysky  说一下我的提议吧，我看这边所有的截图都在windows下的，作者可能不怎么使用linux系统，而一般的跨平台开源软件的文档都是以linux下的编译过程作为模板的，就是因为linux发行版基本上都有完善的包管理系统可以解决依赖问题。而作者的文档只提供了windows下的编译方法，还试图让用户以windows下的编译方法去编译，我想没有哪个linux用户每个软件都装一份明明源里面提供了的依赖库。所以我觉得，作者应该至少提供一个当下主流linux发行版的编译过程，最重要的是要列出依赖的包。
