### ISSUE TITLE
浏览与操作的兼容性问题

### ISSUE THREAD

**Issue by hangitfan** [Greedysky/TTKMusicplayer#74]
刚刚发现这个项目,用readme提供的Executable file版本发现在win7 32bit下有些问题
有些想法希望能交流一下

1.乐库使用了kugou的网页,但是软件内用ie展示内容似乎有些问题,本来单击的操作变成了另外一个操作才能打开链接,js的错误也会直接弹窗,而且所有这些入口访问到的歌曲页面,与请求歌曲文件相关的操作均会提示需要使用kugou新版本.
但如果设置下载源为网易或企鹅源,通过搜索获取的歌曲页面(应该是代码自身生成的),与请求歌曲文件相关的操作才正常
所以我想了解下,是否项目对运行的环境或者浏览器内核有要求,还是kugou的那个页面确实无法工作?
2. 开始播放后,播放栏download功能无法选择对应的资源,造成操作失败,是有意的吗?
3. 猪肉厂的源download时候会502,System.Net.Sockets.SocketException 由于目标计算机积极拒绝，无法连接。 127.0.0.1:80(这个是抓包看到的信息)   

多谢!

**Comment by Greedysky** [comment]
第一个酷狗那个页面暂时还没有找到相关hack方法 所以搜索页面暂时是自己写的。
第二个不是很明白，下载的时候选择对应的比特率条目。
第三个应该是本地网络配置问题

**Comment by hangitfan** [comment]
了解,酷狗的页面看来确实还待完善
第二个是选择播放以后,播放栏的download功能无法选择比特率条目,歌曲或专辑页面上的功能正常
第三个有用网络配置里的连接测试过,好像也没有得出什么问题,开始download只有一个响应,实际文件没有成功取回

**Comment by Greedysky** [comment]
部分歌曲如果是没有版权或者是vip下架歌曲 是没法下载的  把你的测试用例说一下，我调试

**Comment by hangitfan** [comment]
没有版权是指平台是否有版权吗?我是选择企鹅平台后试一下搜索周杰伦,用标准试听稻香成功,搜索结果页面的两个download都可以选择比特率,但是播放栏添加最爱右边的download无法展示比特率项目

**Comment by Greedysky** [comment]
你所描述的这个问题应该是加载显示慢的问题

**Comment by hangitfan** [comment]
![2018-02-04_144808](https://user-images.githubusercontent.com/14119981/35774994-7a34c984-09ba-11e8-955b-a6c73ec7a336.jpg)
试着传个附件,这个地方的窗口不会有资源可以选择的

**Comment by hangitfan** [comment]
真的是加载慢...36s左右的时间
另外下载flac完成以后进程会挂掉,不知道哪里看exception日志

**Comment by Greedysky** [comment]
根目录下有dump文件，你试着分析下

**Comment by hangitfan** [comment]
实在是对dump不了解使不上力,可耻的放弃了....正在发掘功能,希望能有更多回馈
