### ISSUE TITLE
Project ERROR: Could not find qmmp library, please download and put it to output dir

### ISSUE THREAD

**Issue by xiaofangzii** [Greedysky/TTKMusicplayer#78]
Project MESSAGE: Found lrelease executable: /usr/lib/qt4/bin/lrelease
Project ERROR: Could not find qmmp library, please download and put it to output dir
Project ERROR: Could not find qmmp library, please download and put it to output dir
Project MESSAGE: Found Qt web component, build in KuGou by Qt webkit
Project MESSAGE: Found lrelease executable: /usr/bin/lrelease-qt5
Project ERROR: Could not find qmmp library, please download and put it to output dir
Project ERROR: Could not find qmmp library, please download and put it to output dir
Project MESSAGE: Found Qt web component, build in KuGou by Qt webengine

archlinux下，编译出现以上error   qmmp是个什么样的库啊！

**Comment by Greedysky** [comment]
编译请参照 wiki https://github.com/Greedysky/TTKMusicplayer/wiki/%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E
