### ISSUE TITLE
Song Title and Artist Name are not correct 

### ISSUE THREAD

**Issue by zyndin** [Greedysky/TTKMusicplayer#79]
When I search with Korean Title (with data server is QQ Music) and then the result and tags file are not correct

here is the srceenshots

![screenshot 2018-05-05 20 34 13](https://user-images.githubusercontent.com/33575013/39663813-14b66442-50a4-11e8-9ce7-52341552dd34.png)
![screenshot 2018-05-05 20 34 51](https://user-images.githubusercontent.com/33575013/39663814-14ef610c-50a4-11e8-9624-9e563dde0be2.png)

How must I do now?

**Comment by zyndin** [comment]
Thank you so much for fixingqqtext encode. And may I ask you can add Track-Number option 

![screenshot 2018-05-13 08 00 00](https://user-images.githubusercontent.com/33575013/39962805-05bccf72-5684-11e8-88b7-132d682bb4fe.png)

Thanks in advance.

**Comment by Greedysky** [comment]
Add more meta info next version

**Comment by zyndin** [comment]
Hello,

I can't search Wang Yi Music server. May I ask how to search at that server?

Thank you so much for great software.
