### ISSUE TITLE
能不能整理一份各音乐平台的api接口呀

### ISSUE THREAD

**Issue by aeagean** [Greedysky/TTKMusicplayer#81]
方便学习下:grin:

**Comment by rekols** [comment]
API 都在这：https://github.com/Greedysky/TTKMusicplayer/tree/master/TTKModule/TTKCore/musicNetworkKits

**Comment by aeagean** [comment]
太分散了。
写在markdown整理一下吧

**Comment by Greedysky** [comment]
接口在Interface里面定义 可以找到。
