### ISSUE TITLE
为什么不把编译好的程序发上来？

### ISSUE THREAD

**Issue by sonichy** [Greedysky/TTKMusicplayer#88]

**Comment by Greedysky** [comment]
考虑到平台包大小的问题，暂不考虑托管到Github

**Comment by sonichy** [comment]
问题是 gitee 也没有编译好的啊。
TTDownloader 编译成功过，TTKMusicplayer 没有编译成功，而且编译时间特别长，而且发现你喜欢封装库，我认为这样不方便别人学习，我认为把代码复杂化是一种变相闭源。

**Comment by jeffli678** [comment]
README.md里面有百度网盘的下载链接

**Comment by sonichy** [comment]
哦哦哦，在百度盘里，位置不明显啊
