### ISSUE TITLE
编译报错，应该怎么解决呀？

### ISSUE THREAD

**Issue by xinkunlong** [Greedysky/TTKMusicplayer#90]
Project MESSAGE: Not found Qt web component, build in KuGou by no webkit
Project ERROR: Unknown module(s) in QT: x11extras
Makefile:122: recipe for target 'sub-TTKExtras-make_first' failed
make[1]: *** [sub-TTKExtras-make_first] Error 3
make[1]: Leaving directory '/home/kunlong/Desktop/qt_demo/TTKMusicplayer/TTKThirdParty'
Makefile:74: recipe for target 'sub-TTKThirdParty-make_first' failed
make: *** [sub-TTKThirdParty-make_first] Error 2

**Comment by Greedysky** [comment]
安装 qt x11extras 模块
