### ISSUE TITLE
Linux 桌面下的一些问题

### ISSUE THREAD

**Issue by h0cheung** [Greedysky/TTKMusicplayer#93]
1. 整个界面字体及控件大小明显大于其他软件（14寸，1920x1080，缩放比例 1）
2. 桌面歌词窗口的 class 与主窗口一样为 `TTKMusic`，不便于写窗口管理器与混成器规则
3. 桌面歌词整个矩形范围覆盖的部分都会变模糊，预期行为应该是全透明

测试环境：
Arch Linux
KDE xorg + i3wm + picom （替换 kwin）

**Comment by Greedysky** [comment]
感谢反馈，Arch Linux 暂未测试
