### ISSUE TITLE
window平台编译出现错误 

### ISSUE THREAD

**Issue by matudinglin** [Greedysky/TTKMusicplayer#94]
错误：
:-1: error: LNK1104: 无法打开文件“TTKCore.lib”
:-1: error: LNK1104: 无法打开文件“qmmp1.lib”
提问：
debug和release都是同样的结果
在文件目录也找不到相关文件呀？

**Comment by Greedysky** [comment]
msvc 编译需要自己编译插件。
推荐使用mingw。
更多 请查看wiki (https://github.com/Greedysky/TTKMusicplayer/wiki)
