### ISSUE TITLE
怎么安装

### ISSUE THREAD

**Issue by cnvoid** [Greedysky/TTKMusicplayer#95]
这个linux客户端怎么安装啊

**Comment by yuzh496** [comment]
下载Linux最新包后并解压，把解压后的文件夹名重命名为TTKMusicPlayer（或者把版本号去掉），
然后双击并运行文件夹下的AppRun即可运行。

最新的2.11.1版已经可以在Deepin上运行，能够播放本地歌曲，网络歌单显示正常，但播放网络歌曲时会出错。
