### ISSUE TITLE
关于搜索框无法输入中文的问题？

### ISSUE THREAD

**Issue by mr0007th** [Greedysky/TTKMusicplayer#96]
感谢作者，软件很赞。遇到一点小问题：系统是Lubuntu 20.04 64版，在搜索框中无法输入中文。开始以为是输入法的问题，Fcitx和Ibus输入法都试了，输入法QT支持模块都检查了，但还是输入不了中文，不知是什么问题？

**Comment by Greedysky** [comment]
打包未打入输入法插件，已重新打包。
