### ISSUE TITLE
.sc68无法播放

### ISSUE THREAD

**Issue by flyxyz123** [Greedysky/TTKMusicplayer#98]
windows 10\
2.15.0.0版本，网盘下载的

.sc68无法播放

Audio Overload可以播放.sc68，下面是 Audio Overload的SDK，不知道有没有用。\
<https://github.com/nmlgc/aosdk>\
VLC好像也有.sc68的插件。

下面是一个.sc68的文件可做测试，无法直接上传就压缩了一下。\
[TorbyTorrents - RAZOR1911 Tribute intro.zip](https://github.com/Greedysky/TTKMusicplayer/files/6438646/TorbyTorrents.-.RAZOR1911.Tribute.intro.zip)

**Comment by Greedysky** [comment]
感谢反馈，回头我看一下

**Comment by flyxyz123** [comment]
这压缩包里有更多.sc68格式的文件，以便测试。
[sc68.zip](https://github.com/Greedysky/TTKMusicplayer/files/6438893/sc68.zip)
来源：<http://keygenmusic.net/?lang=en>

**Comment by Greedysky** [comment]
Fixed
