### ISSUE TITLE
能否增加一些文件格式的支持

### ISSUE THREAD

**Issue by flyxyz123** [Greedysky/TTKMusicplayer#99]
希望增加的格式：
- .webm
- .ahx
- .amd
- .rad
- .d00
- .mo3
- .bp

VLC支持.webm\
Audio Overload支持.ahx，下面是 Audio Overload的SDK，不知道有没有用。
<https://github.com/nmlgc/aosdk>

amd, rad, d00, mo3, bp我也不知道咋打开

下面链接的一些软件加上插件貌似能打开这些格式，但好像都是闭源的。\
这网站的音乐里有这些格式。\
<http://keygenmusic.net/?page=soft/soft&lang=en>

附带说一句，能播放.v2m真的是太棒了，我还没找到过能播放.v2m的开源软件。

**Comment by Greedysky** [comment]
这些扩展格式我研究下，如果顺利将会出现在后续的开发版本中

**Comment by Greedysky** [comment]
另外可否提供上述格式的文件，以便做测试 @flyxyz123

**Comment by flyxyz123** [comment]
下面的.zip压缩文件里有ahx, amd, bp, d00, mo3, rad格式的一些文件\
[ahx_amd_bp_d00_mo3_rad.zip](https://github.com/Greedysky/TTKMusicplayer/files/6438864/ahx_amd_bp_d00_mo3_rad.zip)\
来源：<http://keygenmusic.net/?lang=en>

.webm格式的文件用youtube-dl下载youtube上的音乐会有很多\
`youtube-dl -f bestaudio some_youtube_link`\
我电脑上的webm文件可能会有版权问题，不太敢发

**Comment by Greedysky** [comment]
支持了.webm .amd .rad .d00格式

**Comment by Greedysky** [comment]
支持了.ahx .hvl格式

**Comment by Greedysky** [comment]
支持了Audio Overload部分格式 bp格式暂时不支持

**Comment by Greedysky** [comment]
支持了BP SoundMon，包括.bp和.bp3 @flyxyz123

**Comment by flyxyz123** [comment]
> 支持了BP SoundMon，包括.bp和.bp3 @flyxyz123

非常感谢！
